#!/usr/bin/env python3
"""
Update the 3 master issues to fill in the real sub-issue numbers in the
checklist. Reads scripts/.issue_map.json.
"""
import json
import subprocess
from pathlib import Path

REPO = "williamokano/german-learning"

B1_LESSONS = [
    ("01", "frueher-und-heute", "Früher und heute"),
    ("02", "gegensaetze-und-folgen", "Gegensätze und Folgen"),
    ("03", "wuensche-und-irreales", "Wünsche und Irreales"),
    ("04", "das-passiv", "Das Passiv"),
    ("05", "relativsaetze-komplett", "Relativsätze komplett"),
    ("06", "ziele-und-absichten", "Ziele und Absichten"),
    ("07", "der-genitiv", "Der Genitiv"),
    ("08", "verben-mit-praepositionen", "Verben mit Präpositionen II"),
    ("09", "indirekte-fragen", "Indirekte Fragen & Höflichkeit"),
    ("10", "zweiteilige-konnektoren", "Zweiteilige Konnektoren"),
    ("11", "arbeitswelt-und-bewerbung", "Arbeitswelt & Bewerbung"),
    ("12", "umwelt-und-gesellschaft", "Umwelt und Gesellschaft"),
    ("13", "schreiben-und-sprechen", "Schreiben und Sprechen B1"),
    ("14", "pruefungstraining-b1", "Prüfungstraining B1 (mock exam)"),
]

B2_LESSONS = [
    ("01", "nominalstil-und-verbalstil", "Nominalstil und Verbalstil"),
    ("02", "passiv-und-alternativen", "Passiv und seine Alternativen"),
    ("03", "vergangenheit-der-moeglichkeit", "Vergangenheit der Möglichkeit"),
    ("04", "indirekte-rede", "Indirekte Rede"),
    ("05", "partizipien-als-attribute", "Partizipien als Attribute"),
    ("06", "modalverben-subjektiv", "Modalverben: subjektive Bedeutung"),
    ("07", "konnektoren-fuer-profis", "Konnektoren für Profis"),
    ("08", "funktionsverbgefuige", "Funktionsverbgefüge & feste Verbindungen"),
    ("09", "wortbildung", "Wortbildung"),
    ("10", "wissenschaft-und-technik", "Wissenschaft und Technik"),
    ("11", "wirtschaft-und-arbeitswelt", "Wirtschaft und Arbeitswelt"),
    ("12", "argumentieren-und-eroertern", "Argumentieren und Erörtern"),
    ("13", "grafiken-und-berichte", "Grafiken und Berichte"),
    ("14", "pruefungstraining-b2", "Prüfungstraining B2"),
]

C1_LESSONS = [
    ("01", "stil-und-register", "Stil und Register"),
    ("02", "komplexe-syntax", "Komplexe Syntax"),
    ("03", "modalpartikeln-und-nuancen", "Modalpartikeln und Nuancen"),
    ("04", "idiomatik-und-kollokationen", "Idiomatik und Kollokationen"),
    ("05", "wissenschaftssprache", "Wissenschaftssprache"),
    ("06", "feinheiten-der-grammatik", "Feinheiten der Grammatik"),
    ("07", "synonymik-und-bedeutungsnuancen", "Synonymik und Bedeutungsnuancen"),
    ("08", "textproduktion-c1", "Textproduktion C1"),
    ("09", "vortrag-und-diskussion", "Vortrag und Diskussion"),
    ("10", "literatur-und-medien", "Literatur und Medien"),
    ("11", "gesellschaft-politik-zukunft", "Gesellschaft, Politik, Zukunft"),
    ("12", "pruefungstraining-c1", "Prüfungstraining C1"),
]


def make_master_body(level, lessons, sub_numbers, master_num):
    n_lessons = len(lessons)
    lines = [
        f"# {level} — Master tracking issue (#{master_num})",
        "",
        f"**{n_lessons} lessons** to author. Each lives in `{level}/<NN>-<slug>/`.",
        "",
        "Per lesson: `lesson.md` + `exercises.yml` (canonical source).",
        "`exercises.md` + `solutions.md` are generated by `npx tsx build/gen-exercises.ts`.",
        "Audio by `python3 scripts/generate_audio.py`.",
        "",
        "Authoring spec: **`AUTHORING.md`**.  Personas: **`personas/README.md`**.",
        "Voice registry: **`scripts/audio_config.json`**.",
        "",
        "**Cast available for B1+:** Anna · Bruno · Mia · Lukas · Yusuf · Hannah · Tomáš · Pavel · Yuki · Frau Weber · Frau Yilmaz · Herr Steinmeyer",
        "",
        "---",
        "",
        "## Lesson checklist",
        "",
    ]
    for (num, slug, title), issue_num in zip(lessons, sub_numbers):
        lines.append(f"- [ ] **{level}/{num}** — {title} → #{issue_num}")
    lines += [
        "",
        "---",
        "",
        "## Definition of Done for the level",
        "",
        f"- [ ] All {n_lessons} sub-issues closed",
        "- [ ] `npx tsx build/gen-exercises.ts --all --check` is green for every lesson in the level",
        "- [ ] Site at `okano.dev/german-learning/{level}/` serves every lesson with audio",
        "- [ ] `tasks/todo.md` checkbox row updated to ✅ DONE for every lesson",
        "- [ ] `CURRICULUM.md` Progress section updated",
        "",
        "---",
        "",
        "## Reference",
        "",
        "- Full B1 plan (in chat history of commit `22e73b8`)",
        "- B2/C1 grammar anchors: `CURRICULUM.md`",
        "- Authoring spec: `AUTHORING.md`",
        "- Personas: `personas/README.md`",
        "- Voice registry: `scripts/audio_config.json`",
        "",
    ]
    return "\n".join(lines)


def gh_issue_edit(num, body):
    res = subprocess.run(
        ["gh", "issue", "edit", str(num), "--body", body, "--repo", REPO],
        capture_output=True, text=True,
    )
    if res.returncode != 0:
        print(f"  ✗ #{num}: {res.stderr.strip()[:200]}", flush=True)
        return False
    print(f"  ✓ #{num} updated", flush=True)
    return True


def main():
    issue_map = json.loads(Path("scripts/.issue_map.json").read_text())
    masters = issue_map["masters"]
    subs    = issue_map["subs"]

    for level, lessons, sub_nums in [
        ("B1", B1_LESSONS, subs["B1"]),
        ("B2", B2_LESSONS, subs["B2"]),
        ("C1", C1_LESSONS, subs["C1"]),
    ]:
        body = make_master_body(level, lessons, sub_nums, masters[level])
        gh_issue_edit(masters[level], body)


if __name__ == "__main__":
    main()
